#!/bin/bash

#var
screen=$(xrandr | grep ' connected' | awk {'print $1'})
screenstate='/tmp/escuro.tmp'

#func
reset_gamma(){
	xrandr --output $screen --gamma 1.0:1.0:1.0
}

set_nightlight_gamma(){
	xrandr --output $screen --gamma 0.95:0.8:0.65
}

#boom

find $screenstate > /dev/null && \
	[ $(cat $screenstate) == 1 ] && reset_gamma && echo '0' > $screenstate || { set_nightlight_gamma && echo '1' > $screenstate; }



###############ANTIGO##########################################
#if [ -f $screenstate ]; then
#	if [ $(cat $screenstate) == 1 ]; then
#		reset_gamma && echo 0 > $screenstate
#	else
#		set_nightlight_gamma && echo 1 > $screenstate
#	fi
#else
#	set_nightlight_gamma && echo 1 > $screenstate
#fi
###############################################################
